GET http://localhost:9999

### -> Request: Error
GET http://localhost:9999/localhost:9999/abc-xyz

### -> Get all Products
GET http://localhost:9999/products

### -> Get product by _id
GET http://localhost:9999/products/65b676a2fc187f6446946ff0

### -> Add new product
POST http://localhost:9999/products
Content-Type: application/json

{
  "name": "Product 4",
  "price": 30,
  "description": "Product 3 description",
  "images": [],
  "comments": [],
  "category": "65b5208ec73b4cedee28eb04"
}

### -> Get all Categories
GET http://localhost:9999/categories